DROP DATABASE IF EXISTS HERO_DB;

CREATE DATABASE HERO_DB;

\C HERO_DB;

DROP TABLE IF EXISTS STATS;

CREATE TABLE STATS (
    KEY SERIAL PRIMARY KEY,
    ALIAS TEXT NOT NULL,
    LASTNAME TEXT NOT NULL,
    DOB DATE NOT NULL,
    ADULT BOOLEAN NOT NULL
);